---
- name: "Install packages"
  retries: 3
  delay: 10
  until: output is success
  register: output
  ansible.builtin.package:
    update_cache: true
    name:
      - "apt-transport-https"
      - "software-properties-common"
      - "wget"

- name: "Install Grafana"
  notify: "Enable and start Grafana"
  block:
    - name: "Add Grafana GPG apt Key"
      ansible.builtin.apt_key:
        url: "https://apt.grafana.com/gpg.key"

    - name: "Add Grafana Repository"
      ansible.builtin.apt_repository:
        repo: "deb https://apt.grafana.com stable main"

    - name: "Update apt and install Grafana"
      ansible.builtin.apt:
        update_cache: true
        name:
          - "grafana"

- name: "Import Grafana conf"
  notify: "Restart Grafana"
  block:
    - name: "Check if data folder exist"
      register: file_check
      ansible.builtin.stat:
        path: "{{ install_grafana__data }}"

    - name: "Create data dir"
      when: not file_check.stat.exists
      ansible.builtin.file:
        path: "{{ install_grafana__data }}"
        state: directory
        recurse: yes
        owner: "{{ install_grafana__user }}"
        group: "{{ install_grafana__group }}"
        mode: "0700"

    - name: "Import Grafana conf"
      ansible.builtin.template:
        src: "templates/grafana.ini.j2"
        dest: "/etc/grafana/grafana.ini"
        lstrip_blocks: yes
        owner: "{{ install_grafana__user }}"
        group: "{{ install_grafana__group }}"
        mode: "0700"

    - name: "Import Grafana /etc/default"
      ansible.builtin.template:
        src: "templates/grafana-server.j2"
        dest: "/etc/default/grafana-server"
        owner: "{{ install_grafana__user }}"
        group: "{{ install_grafana__group }}"
        mode: "0700"
        lstrip_blocks: yes

- name: "Import Grafana service file"
  notify:
    - "Enable and start Grafana"
    - "Restart Grafana"
  ansible.builtin.template:
    src: "templates/grafana-server.service.j2"
    dest: "/usr/lib/systemd/system/grafana-server.service"
    mode: "0600"
    group: "root"
    owner: "root"
    lstrip_blocks: yes
