---
- name: "Enable and start Grafana"
  register: install_grafana__service_status
  changed_when: install_grafana__service_status.state != "started"
  ansible.builtin.service:
    name: "grafana-server"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart Grafana"
  register: install_grafana__service_status
  changed_when: install_grafana__service_status.state != "restarted"
  ansible.builtin.service:
    name: "grafana-server"
    state: "restarted"
    daemon_reload: true
