---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_grafana"
      tags:
        - "labocbz.install_grafana"
      vars:
        install_grafana__app_mode: "{{ inv_install_grafana__app_mode }}"
        install_grafana__data: "{{ inv_install_grafana__data }}"
        install_grafana__temp_data_lifetime: "{{ inv_install_grafana__temp_data_lifetime }}"
        install_grafana__protocol: "{{ inv_install_grafana__protocol }}"
        install_grafana__min_tls_version: "{{ inv_install_grafana__min_tls_version }}"
        install_grafana__http_addr: "{{ inv_install_grafana__http_addr }}"
        install_grafana__http_port: "{{ inv_install_grafana__http_port }}"
        install_grafana__domain: "{{ inv_install_grafana__domain }}"
        install_grafana__enforce_domain: "{{ inv_install_grafana__enforce_domain }}"
        install_grafana__root_url: "{{ inv_install_grafana__root_url }}"
        install_grafana__serve_from_sub_path: "{{ inv_install_grafana__serve_from_sub_path }}"
        install_grafana__router_logging: "{{ inv_install_grafana__router_logging }}"
        install_grafana__enable_gzip: "{{ inv_install_grafana__enable_gzip }}"
        install_grafana__cert_file: "{{ inv_install_grafana__cert_file }}"
        install_grafana__cert_key: "{{ inv_install_grafana__cert_key }}"
        install_grafana__log_mode: "{{ inv_install_grafana__log_mode }}"
        install_grafana__log_level: "{{ inv_install_grafana__log_level }}"
        install_grafana__log_max_days: "{{ inv_install_grafana__log_max_days }}"
      ansible.builtin.include_role:
        name: "labocbz.install_grafana"
